name: progk
favicon: null
layout_spectrum: 0.488890266045928
typography_spectrum: 0.5639458026271313
title: Programkonstruktion Svenska AB
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ed1c24'
    - '#7b7979'
    - '#3d3a3b'
    - '#f3666c'
  brandStrength: 0.8704021442681551
  lightness: 0.32012621429748833
  saturation: 0.8973283255472779
  rhythmicContrast: 0.8327202843502164
purpose: []
